version: '3.1'

services:

  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=${PMA_HOST}
      - PMA_ABSOLUTE_URI=http://localhost:8081
    ports:
      - "8081:80"
    networks:
      - default

  web:
    image: ghcr.io/asjordi/webapp-todo:main
#    image: asjordi/webapp-todo:1.0.0
    container_name: webapp-todo
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    networks:
      - default

volumes:
  mysql-data:
    external: true

networks:
  default:
    driver: bridge